name: 'webfactory/create-aws-codedeploy-deployment'
description: 'Really useful'
inputs:
    aws-region:
        default: eu-central-1
    application-name:
        description: 'AWS CodeDeploy application name'
        required: true
runs:
    using: 'node12'
    main: 'dist/index.js'
