# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: deployment.sh
  AfterInstall:
    - location: deployment.sh
  ApplicationStart:
    - location: deployment.sh
  ValidateService:
    - location: deployment.sh

branch_config:
    master: ~
    dependabot\/.*: ~

    '.*':
        deploymentGroupName: test-$BRANCH.test.webfactory.de
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::279767678935:role/CodeDeployServiceRole
            ec2TagFilters:
                - { Type: KEY_AND_VALUE, Key: Name, Value: testaroli.ec2.webfactory.de }
        deploymentConfig:
            autoRollbackConfiguration:
                enabled: false
#            autoRollbackConfiguration:
#                enabled: true
#                events: ['DEPLOYMENT_FAILURE', 'DEPLOYMENT_STOP_ON_ALARM', 'DEPLOYMENT_STOP_ON_REQUEST']
