# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: .aws/codedeploy
  BeforeInstall:
      - location: .aws/codedeploy
  AfterInstall:
      - location: .aws/codedeploy
  ApplicationStart:
      - location: .aws/codedeploy
  ValidateService:
      - location: .aws/codedeploy

branch_config:
    master: ~

    dependabot\/.*: ~

    '.*':
        deploymentGroupName: test-$BRANCH.test.webfactory.de
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::279767678935:role/CodeDeployServiceRole
            ec2TagFilters:
                - { Type: KEY_AND_VALUE, Key: Name, Value: testaroli.ec2.webfactory.de }
